### ISSUE TITLE
POST /apis  can't add multiple endpoints from one file

### ISSUE THREAD

**Issue by newthinker** [motiv-labs/janus#246]
Can't add multiple endpoints from the api file and the response is:

```"error":"json: cannot unmarshal array into Go value of type api.definitionAlias","level":"error","msg":"Internal server error handled",

goroutine 59 [running]:
runtime/debug.Stack(0x16, 0x16, 0x16)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/hellofresh/janus/pkg/errors.Handler(0x111ece0, 0xc4203d4240, 0xaf1780, 0xc42042e8c0)
	/rc/local/go/src/github.com/hellofresh/janus/pkg/errors/error.go:62 +0x6a
github.com/hellofresh/janus/pkg/api.(*Controller).Post.func1(0x111ece0, 0xc4203d4240, 0xc420106e00)
	/rc/local/go/src/github.com/hellofresh/janus/pkg/api/handler.go:122 +0x364
net/http.HandlerFunc.ServeHTTP(0xc42031e420, 0x111ece0, 0xc4203d4240, 0xc420106e00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/hellofresh/janus/vendor/github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0xc420351a00, 0x111ece0, 0xc4203d4240, 0xc420106e00)
	/rc/local/go/src/github.com/hellofresh/janus/vendor/github.com/go-chi/chi/chain.go:31 +0x52
github.com/hellofresh/janus/vendor/github.com/go-chi/chi.(*Mux).routeHTTP(0xc420102a10, 0x111ece0, 0xc4203d4240, 0xc420106e00)
	/rc/local/go/src/github.com/hellofresh/janus/vendor/github.com/go-chi/chi/mux.go:407 +0x2f4
github.com/hellofresh/janus/vendor/github.com/go-chi/chi.(*Mux).(github.com/hellofresh/janus/vendor/github.com/go-chi/chi.routeHTTP)-fm(0x111ece0, 0xc4203d4240, 0xc420106e00)
	/rc/local/go/src/github.com/hellofresh/janus/vendor/github.com/go-chi/chi/mux.go:354 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42031e3d0, 0x111ece0, 0xc4203d4240, 0xc420106e00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/hellofresh/janus/pkg/jwt.(*Middleware).Handler.func1(0x111ece0, 0xc4203d4240, 0xc420106e00)
	/rc/local/go/src/github.com/hellofresh/janus/pkg/jwt/middleware.go:40 +0x19c
net/http.HandlerFunc.ServeHTTP(0xc4200eae40, 0x111ece0, 0xc4203d4240, 0xc420106e00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/hellofresh/janus/vendor/github.com/go-chi/chi.(*Mux).ServeHTTP(0xc420102a10, 0x111ece0, 0xc4203d4240, 0xc420106e00)
	/rc/local/go/src/github.com/hellofresh/janus/vendor/github.com/go-chi/chi/mux.go:69 +0x290
github.com/hellofresh/janus/vendor/github.com/go-chi/chi.(*Mux).Mount.func1(0x111ece0, 0xc4203d4240, 0xc420106e00)
	/rc/local/go/src/github.com/hellofresh/janus/vendor/github.com/go-chi/chi/mux.go:295 +0x104
net/http.HandlerFunc.ServeHTTP(0xc4200eada0, 0x111ece0, 0xc4203d4240, 0xc420106e00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/hellofresh/janus/vendor/github.com/go-chi/chi.(*Mux).routeHTTP(0xc420102230, 0x111ece0, 0xc4203d4240, 0xc420106e00)
	/rc/local/go/src/github.com/hellofresh/janus/vendor/github.com/go-chi/chi/mux.go:407 +0x2f4
github.com/hellofresh/janus/vendor/github.com/go-chi/chi.(*Mux).(github.com/hellofresh/janus/vendor/github.com/go-chi/chi.routeHTTP)-fm(0x111ece0, 0xc4203d4240, 0xc420106e00)
	/rc/local/go/src/github.com/hellofresh/janus/vendor/github.com/go-chi/chi/mux.go:354 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42031e290, 0x111ece0, 0xc4203d4240, 0xc420106e00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/hellofresh/janus/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x111ece0, 0xc4203d4240, 0xc420106e00)
	/rc/local/go/src/github.com/hellofresh/janus/vendor/github.com/rs/cors/cors.go:200 +0x108
net/http.HandlerFunc.ServeHTTP(0xc4200ea540, 0x111ece0, 0xc4203d4240, 0xc420106e00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/hellofresh/janus/pkg/middleware.(*OpenTracing).Handler.func1(0x111ece0, 0xc4203d4240, 0xc420106a00)
	/rc/local/go/src/github.com/hellofresh/janus/pkg/middleware/opentracing.go:78 +0x72d
net/http.HandlerFunc.ServeHTTP(0xc4200ea560, 0x111ece0, 0xc4203d4240, 0xc420106a00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/hellofresh/janus/pkg/middleware.NewRecovery.func1.1(0x111ece0, 0xc4203d4240, 0xc420106a00)
	/rc/local/go/src/github.com/hellofresh/janus/pkg/middleware/recovery.go:15 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc4200ea5e0, 0x111ece0, 0xc4203d4240, 0xc420106a00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/hellofresh/janus/pkg/middleware.(*Logger).Handler.func1(0x111d5e0, 0xc4203d4200, 0xc420106a00)
	/rc/local/go/src/github.com/hellofresh/janus/pkg/middleware/logger.go:57 +0x80c
net/http.HandlerFunc.ServeHTTP(0xc4200ea600, 0x111d5e0, 0xc4203d4200, 0xc420106a00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/hellofresh/janus/vendor/github.com/go-chi/chi/middleware.Compress.func1.1(0x111e220, 0xc4204c07e0, 0xc420106a00)
	/rc/local/go/src/github.com/hellofresh/janus/vendor/github.com/go-chi/chi/middleware/compress.go:66 +0x15b
net/http.HandlerFunc.ServeHTTP(0xc42000ec90, 0x111e220, 0xc4204c07e0, 0xc420106a00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/hellofresh/janus/vendor/github.com/go-chi/chi/middleware.StripSlashes.func1(0x111e220, 0xc4204c07e0, 0xc420106a00)
	/rc/local/go/src/github.com/hellofresh/janus/vendor/github.com/go-chi/chi/middleware/strip.go:24 +0xce
net/http.HandlerFunc.ServeHTTP(0xc4200ea640, 0x111e220, 0xc4204c07e0, 0xc420106a00)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/hellofresh/janus/vendor/github.com/go-chi/chi.(*Mux).ServeHTTP(0xc420102230, 0x111e220, 0xc4204c07e0, 0xc420106700)
	/rc/local/go/src/github.com/hellofresh/janus/vendor/github.com/go-chi/chi/mux.go:80 +0x1d4
github.com/hellofresh/janus/pkg/router.(*ChiRouter).ServeHTTP(0xc42031e1f0, 0x111e220, 0xc4204c07e0, 0xc420106700)
	/rc/local/go/src/github.com/hellofresh/janus/pkg/router/chi.go:32 +0x54
net/http.serverHandler.ServeHTTP(0xc4200768f0, 0x111e220, 0xc4204c07e0, 0xc420106700)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420448000, 0x111f1e0, 0xc4203d4040)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
```

**Reproduction Steps:**

1. run the janus service
2. login the janus and get the bearer token
3. load the api files with the bearer token

**Expected behavior:**

load apis from the files

**Observed behavior:**

added failed, but success when there is only one api in the file

**Janus version:** Janus v3.4.1-4386326
**OS and version:** CentOS Linux release 7.4.1708

**Comment by rafaeljesus** [comment]
Hi @newthinker thanks for reporting this,

We're looking into this asap, however that would be great if you could provide the proxy definition contents

**Comment by rafaeljesus** [comment]
> github.com/hellofresh/janus/pkg/api.(*Controller).Post.func1(0x111ece0, 0xc4203d4240, 0xc420106e00)

@newthinker I guess you are trying to create multiple proxy definitions via API right? This feature was added recently https://github.com/hellofresh/janus/pull/228 it is only supported when persistence storage is [file system](https://github.com/marcelnubi/janus/blob/master/docs/quick_start/file_system.md) you can't do that via the API

**Comment by newthinker** [comment]
@rafaeljesus yes, i did it via the API indeed and i'll test the file system type. Thank you very much.

**Comment by rafaeljesus** [comment]
Anytime 👍
